
in_raw:
  T1w: /project/6050199/akhanf/ext-bids/developing_human_connectome/bids/sub-{subject}/anat/sub-{subject}_rec-SVR_T1w.nii.gz
  T2w: /project/6050199/akhanf/ext-bids/developing_human_connectome/bids/sub-{subject}/anat/sub-{subject}_rec-SVR_T2w.nii.gz

#pre-processed / co-registered images for template building 
in_images:
  T1w: 'results/preproc/sub-{subject}/sub-{subject}_desc-n4_T1w.nii.gz'
  T2w: 'results/preproc/sub-{subject}/sub-{subject}_space-T1w_desc-n4_T2w.nii.gz'


#for naming the final files in templateflow output
bids_suffix:
  T1w: 'desc-brain_T1w'
  T2w: 'desc-brain_T2w'
  GM: 'label-GM_probseg'
  WM: 'label-WM_probseg'



cohorts:
  - neonatal92T1T2

participants_tsv:
  neonatal92T1T2: 'config/participants_neonatal_t1t2.tsv'
  


#for templateflow-style output
template_name: 'dHCP'  #tpl-{template_name} 



resolution_index: 1 # res-{resolution_index}
#shape, zooms, origin will be obtained from the nifti itself


#for creating the template_description.json file
template_description_extras:
  Name: 'Brief template description goes here'
  Authors:
    - 'Your Name Here'
  Acknowledgements: 'Created by ants_build_template_smk Snakemake workflow'
  BIDSVersion:
    - '1.1.0' 
  License: 'See LICENSE file'
  TemplateFlowVersion: '1.0.0'


#assumes that templateflow templates are linked in resources folder
init_template:
  T1w: 'results/preproc/sub-CC00051XX02/sub-CC00051XX02_desc-n4_T1w.nii.gz'
  T2w: 'results/preproc/sub-CC00051XX02/sub-CC00051XX02_space-T1w_desc-n4_T2w.nii.gz'


std_template:
  T1w: /project/6050199/ext-data/neonatal_brain_atlases/Serag_2012_204subj_T1_T2_probmaps/split_ga/template_ga-44_T1.nii.gz
  T2w: /project/6050199/ext-data/neonatal_brain_atlases/Serag_2012_204subj_T1_T2_probmaps/split_ga/template_ga-44_T2.nii.gz
 

#will register cohort templates to the std template after they are generated
std_template_name: 'SeragNeonatal'

#keep this empty, is set by command-line ( --config run_iter=1 or --config run_cohort=young)
run_cohort: 
run_iter: 

#this is the iter which is exported into templateflow format
max_iters: 5


resample_init_template: False #set this True to resample init template to below dims 
# WARNING - changing this can significantly alter memory usage and run-time -- 

resample_vox_dims: 
 - 1
 - 1
 - 1

resample_std_template: True

resample_std_vox_dims:
 - 0.5
 - 0.5
 - 0.5


#should be at least 2.3.4 (includes --random-seed option, and fixes some argparsing bugs)
singularity:
  prepdwi: '/project/6050199/akhanf/singularity/bids-apps/khanlab_prepdwi_latest.sif'  
  ants:  '/project/6050199/akhanf/singularity/kaczmarj_ants_2.3.4.sif'
  itksnap:  '/project/6050199/akhanf/singularity/pyushkevich_itksnap_latest.sif'

ants:
  dim: 3
  shape_update:
      gradient_step: 0.25



